from pathlib import Path
from pydantic import Field, AliasChoices
from pydantic_settings import BaseSettings

# Anchored to this file's location, not the process's current working
# directory — pydantic-settings resolves a relative env_file against CWD at
# launch, so starting uvicorn from anywhere other than backend/ silently
# finds no .env and every setting falls back to its hardcoded default
# (empty API keys, etc.) with no error.
_ENV_FILE = Path(__file__).resolve().parent.parent.parent / ".env"


class Settings(BaseSettings):
    database_url: str = (
        "postgresql+asyncpg://postgres:password@localhost:5432/worklearn"
    )
    jwt_secret: str = "dev-secret"
    jwt_algorithm: str = "HS256"
    jwt_expire_days: int = 7
    # ADMIN/SUPER_ADMIN tokens use a shorter expiry than the student default —
    # these accounts can mutate other accounts/data, so a stolen/leaked token
    # has a smaller window of usefulness.
    admin_jwt_expire_hours: int = 24
    anthropic_api_key: str = ""
    gemini_api_key: str = ""
    groq_api_key: str = ""
    ai_provider: str = "anthropic"  # anthropic | gemini | groq | openai | litellm_proxy

    # "openai" here means any OpenAI-Chat-Completions-compatible endpoint,
    # not necessarily api.openai.com — e.g. a self-hosted vLLM/ngrok server.
    # base_url/model must both be set for this provider to work.
    openai_base_url: str = "https://api.openai.com/v1"
    openai_api_key: str = ""
    openai_model: str = "gpt-4o-mini"

    # LiteLLM Proxy — a standalone AI gateway (see backend/litellm-proxy/),
    # distinct from the in-process litellm SDK usage every other AI_PROVIDER
    # value uses. Only read when ai_provider == "litellm_proxy". The API key
    # here is a virtual key generated BY the proxy (`/key/generate`), never a
    # real provider's own key — those live only in the proxy's own config.
    litellm_proxy_url: str = "http://localhost:4000"
    litellm_proxy_api_key: str = ""
    litellm_proxy_model: str = "llama-groq"
    # Not read by this app at all — it's the litellm-proxy *container's* own
    # admin key (docker-compose.yml passes it through via --env-file
    # backend/.env). Declared here purely so pydantic-settings doesn't reject
    # backend/.env for containing a key this Settings class otherwise
    # wouldn't recognize.
    litellm_master_key: str = ""

    frontend_url: str = "http://localhost:5173"
    port: int = 3001

    # Standard library logging level for the whole app (also gates SQLAlchemy
    # SQL echo — see app/db/database.py). One knob instead of a separate DEBUG
    # bool, so the two can't drift out of sync.
    log_level: str = "INFO"

    # Langfuse tracing — tracing is skipped entirely (no overhead, no log
    # noise) unless both keys are set. See app/ai/services/langfuse_client.py.
    langfuse_public_key: str = ""
    langfuse_secret_key: str = ""
    # Langfuse's own docs/UI call this "Base URL" in some places and "Host"
    # (the actual Python SDK env var) in others — accept either env var name
    # so LANGFUSE_BASE_URL doesn't blow up startup with "extra_forbidden".
    langfuse_host: str = Field(
        default="https://cloud.langfuse.com",
        validation_alias=AliasChoices("LANGFUSE_HOST", "LANGFUSE_BASE_URL"),
    )

    # Sandbox: docker daemon must be installed on the host and the image
    # pre-built — see backend/sandboxes/README.md
    sandbox_image: str = "worklearn-sandbox-python:latest"
    sandbox_image_frontend: str = "worklearn-sandbox-frontend:latest"
    sandbox_timeout_seconds: int = 15
    sandbox_memory_limit: str = "256m"
    sandbox_cpu_limit: str = "0.5"

    # Sandbox runner: "docker" runs `docker run` on the host daemon (local
    # dev); "kubernetes" launches each submission as a Job in sandbox_namespace
    # (in-cluster deployment — see k8s/README.md).
    sandbox_runner: str = "docker"
    sandbox_namespace: str = "worklearn-sandbox"
    # Directory the backend mounts submission workdirs under (must be the same
    # underlying storage the sandbox_hostpath_dir node path resolves to).
    sandbox_shared_dir: str = "/sandbox-work"
    # Node-local path backing sandbox_shared_dir, used in the Job's hostPath
    # volume so sandbox pods see the same files (single-node assumption).
    sandbox_hostpath_dir: str = "/worklearn/sandbox-work"
    sandbox_startup_timeout_seconds: int = 30

    class Config:
        env_file = _ENV_FILE


settings = Settings()

# ── Skill Engine constants ────────────────────────────────────────────────────
# Per-simulation, per-task XP/skill awards and task names used to live here as
# hardcoded dicts (keyed by simulation_id then task_id). They're now columns
# on SimulationTask (xp_award, skill_awards, title) — see app/models/cms.py
# and app/services/skill_engine.py's award_task_completion(). The dicts below
# are genuinely global product config (role-readiness thresholds, skill
# display names), not per-simulation content, so they stay here.

TARGET_ROLE_REQUIREMENTS: dict[str, dict[str, int]] = {
    "junior_da": {
        "sql": 60,
        "python": 50,
        "analytics": 60,
        "data_viz": 40,
        "statistics": 40,
        "communication": 50,
        "data_cleaning": 50,
        "customer_analysis": 30,
        "segmentation": 30,
        "hypothesis_testing": 35,
        "data_storytelling": 40,
    },
    "senior_da": {
        "sql": 80,
        "python": 75,
        "analytics": 85,
        "data_viz": 65,
        "statistics": 70,
        "communication": 70,
        "data_cleaning": 75,
        "customer_analysis": 60,
        "segmentation": 60,
        "hypothesis_testing": 65,
        "data_storytelling": 70,
    },
    "junior_frontend_dev": {
        "html_css": 60,
        "accessibility": 40,
        "javascript": 60,
        "async_data": 40,
        "react": 55,
        "component_design": 40,
        "state_management": 35,
    },
    "junior_sales_rep": {
        "sales_research": 40,
        "email_writing": 40,
        "discovery": 50,
        "crm_accuracy": 50,
        "objection_handling": 45,
        "negotiation": 40,
        "closing": 45,
        "communication": 55,
    },
}

SKILL_LABELS: dict[str, str] = {
    "sql": "SQL & Querying",
    "python": "Python for Data",
    "analytics": "Data Analytics",
    "data_viz": "Data Visualization",
    "statistics": "Statistical Analysis",
    "communication": "Communication",
    "data_cleaning": "Data Cleaning",
    "customer_analysis": "Customer Analysis",
    "segmentation": "Segmentation",
    "hypothesis_testing": "Hypothesis Testing",
    "data_storytelling": "Data Storytelling",
    "html_css": "HTML & CSS",
    "accessibility": "Accessibility",
    "javascript": "JavaScript",
    "async_data": "Async Data Fetching",
    "react": "React",
    "component_design": "Component Design",
    "state_management": "State Management",
    "sales_research": "Sales Research",
    "email_writing": "Email Writing",
    "discovery": "Discovery & Qualification",
    "crm_accuracy": "CRM Accuracy",
    "objection_handling": "Objection Handling",
    "negotiation": "Negotiation",
    "closing": "Closing",
}

QUIZ_BONUS_THRESHOLD = 80
QUIZ_BONUS_XP = 20
INACTIVITY_DAYS = 3
