from pathlib import Path
from pydantic import Field, AliasChoices
from pydantic_settings import BaseSettings

# Anchored to this file's location, not the process's current working
# directory — pydantic-settings resolves a relative env_file against CWD at
# launch, so starting uvicorn from anywhere other than backend/ silently
# finds no .env and every setting falls back to its hardcoded default
# (empty API keys, etc.) with no error.
_ENV_FILE = Path(__file__).resolve().parent.parent.parent / ".env"


class Settings(BaseSettings):
    database_url: str = (
        "postgresql+asyncpg://postgres:password@localhost:5432/worklearn"
    )
    jwt_secret: str = "dev-secret"
    jwt_algorithm: str = "HS256"
    jwt_expire_days: int = 7
    # ADMIN/SUPER_ADMIN tokens use a shorter expiry than the student default —
    # these accounts can mutate other accounts/data, so a stolen/leaked token
    # has a smaller window of usefulness.
    admin_jwt_expire_hours: int = 24
    anthropic_api_key: str = ""
    gemini_api_key: str = ""
    groq_api_key: str = ""
    ai_provider: str = "anthropic"  # anthropic | gemini | groq | openai | litellm_proxy

    # "openai" here means any OpenAI-Chat-Completions-compatible endpoint,
    # not necessarily api.openai.com — e.g. a self-hosted vLLM/ngrok server.
    # base_url/model must both be set for this provider to work.
    openai_base_url: str = "https://api.openai.com/v1"
    openai_api_key: str = ""
    openai_model: str = "gpt-4o-mini"

    # LiteLLM Proxy — a standalone AI gateway (see backend/litellm-proxy/),
    # distinct from the in-process litellm SDK usage every other AI_PROVIDER
    # value uses. Only read when ai_provider == "litellm_proxy". The API key
    # here is a virtual key generated BY the proxy (`/key/generate`), never a
    # real provider's own key — those live only in the proxy's own config.
    litellm_proxy_url: str = "http://localhost:4000"
    litellm_proxy_api_key: str = ""
    litellm_proxy_model: str = "llama-groq"
    # Not read by this app at all — it's the litellm-proxy *container's* own
    # admin key (docker-compose.yml passes it through via --env-file
    # backend/.env). Declared here purely so pydantic-settings doesn't reject
    # backend/.env for containing a key this Settings class otherwise
    # wouldn't recognize.
    litellm_master_key: str = ""

    # Caps how many LLM calls (any AI_PROVIDER — Mentor chat, roleplay,
    # sandbox hints, grading judges) are in flight to the provider AT ONCE,
    # across every request the backend is currently serving. Without this, a
    # burst of students hitting AI-backed endpoints at the same moment fans
    # out one real provider request per request — easily past the provider's
    # own per-account rate limit, and a rate-limited call fails immediately
    # rather than retrying (see llm.py's _is_transient_connection_error).
    # Requests past this cap simply wait their turn locally instead of all
    # landing on the provider together. Start conservative; raise it once you
    # know your actual provider/model's real RPM ceiling — Groq's varies by
    # model and account tier, and if you're behind the LiteLLM Proxy this
    # should stay well under whatever rpm_limit the virtual key carries.
    ai_max_concurrent_calls: int = 8

    frontend_url: str = "http://localhost:5173"
    port: int = 3001

    # Standard library logging level for the whole app (also gates SQLAlchemy
    # SQL echo — see app/db/database.py). One knob instead of a separate DEBUG
    # bool, so the two can't drift out of sync.
    log_level: str = "INFO"

    # Langfuse tracing — tracing is skipped entirely (no overhead, no log
    # noise) unless both keys are set. See app/ai/services/langfuse_client.py.
    langfuse_public_key: str = ""
    langfuse_secret_key: str = ""
    # Langfuse's own docs/UI call this "Base URL" in some places and "Host"
    # (the actual Python SDK env var) in others — accept either env var name
    # so LANGFUSE_BASE_URL doesn't blow up startup with "extra_forbidden".
    langfuse_host: str = Field(
        default="https://cloud.langfuse.com",
        validation_alias=AliasChoices("LANGFUSE_HOST", "LANGFUSE_BASE_URL"),
    )

    # Sandbox: docker daemon must be installed on the host and the image
    # pre-built — see backend/sandboxes/README.md
    sandbox_image: str = "worklearn-sandbox-python:latest"
    sandbox_image_frontend: str = "worklearn-sandbox-frontend:latest"
    # Headroom, measured rather than guessed: a passing frontend submission
    # (container start + Jest + jsdom) takes ~6s wall clock at 0.5 CPU, so the
    # old 15s limit left barely 2.4x — one busy host or two students
    # submitting at once and a perfectly good answer silently scores 0, since
    # a timeout means no output.json and the grader can only report "no
    # report produced". These are the safety limits for untrusted code, not a
    # performance budget; there is no reason to run them this close to the
    # edge. Raising CPU also cuts the wall clock, which shortens the window in
    # which a browser tab can be backgrounded mid-request.
    #
    # 256m was tight for Jest+jsdom and for pandas over the ~9,600-row
    # da-job-sim dataset; an OOM kill looks exactly like a timeout to the
    # grader (no artifact), which is precisely the failure that is hardest to
    # diagnose from the outside.
    sandbox_timeout_seconds: int = 45
    sandbox_memory_limit: str = "512m"
    sandbox_cpu_limit: str = "1.0"

    # Sandbox runner: "docker" runs `docker run` on the host daemon (local
    # dev); "kubernetes" launches each submission as a Job in sandbox_namespace
    # (in-cluster deployment — see k8s/README.md).
    sandbox_runner: str = "docker"
    sandbox_namespace: str = "worklearn-sandbox"
    # Directory the backend mounts submission workdirs under (must be the same
    # underlying storage the sandbox_hostpath_dir node path resolves to).
    sandbox_shared_dir: str = "/sandbox-work"
    # Node-local path backing sandbox_shared_dir, used in the Job's hostPath
    # volume so sandbox pods see the same files (single-node assumption).
    sandbox_hostpath_dir: str = "/worklearn/sandbox-work"
    sandbox_startup_timeout_seconds: int = 30

    class Config:
        env_file = _ENV_FILE


settings = Settings()

# ── Skill Engine constants ────────────────────────────────────────────────────
# Per-simulation, per-task XP/skill awards and task names used to live here as
# hardcoded dicts (keyed by simulation_id then task_id). They're now columns
# on SimulationTask (xp_award, skill_awards, title) — see app/models/cms.py
# and app/services/skill_engine.py's award_task_completion(). The dicts below
# are genuinely global product config (role-readiness thresholds, skill
# display names), not per-simulation content, so they stay here.

TARGET_ROLE_REQUIREMENTS: dict[str, dict[str, int]] = {
    "junior_da": {
        "sql": 60,
        "python": 50,
        "analytics": 60,
        "data_viz": 40,
        "statistics": 40,
        "communication": 50,
        "data_cleaning": 50,
        "customer_analysis": 30,
        "segmentation": 30,
        "hypothesis_testing": 35,
        "data_storytelling": 40,
    },
    "senior_da": {
        "sql": 80,
        "python": 75,
        "analytics": 85,
        "data_viz": 65,
        "statistics": 70,
        "communication": 70,
        "data_cleaning": 75,
        "customer_analysis": 60,
        "segmentation": 60,
        "hypothesis_testing": 65,
        "data_storytelling": 70,
    },
    "junior_frontend_dev": {
        "html_css": 60,
        "accessibility": 40,
        "javascript": 60,
        "async_data": 40,
        "react": 55,
        "component_design": 40,
        "state_management": 35,
    },
    "junior_sales_rep": {
        "sales_research": 40,
        "email_writing": 40,
        "discovery": 50,
        "crm_accuracy": 50,
        "objection_handling": 45,
        "negotiation": 40,
        "closing": 45,
        "communication": 55,
    },
    # The two senior tiers below were added so that every track is a real
    # ladder. Before them the Skill GPS UI offered "Mid-level DA" and "Lead DA"
    # — neither of which exists here — and compute_skill_gps' .get(role,
    # junior_da) fallback quietly served Junior DA numbers under those labels.
    # A role that is not a key in this dict is now a 404, not a silent swap.
    "senior_frontend_dev": {
        "html_css": 80,
        "accessibility": 65,
        "javascript": 80,
        "async_data": 65,
        "react": 80,
        "component_design": 70,
        "state_management": 65,
    },
    "senior_sales_rep": {
        "sales_research": 65,
        "email_writing": 60,
        "discovery": 75,
        "crm_accuracy": 70,
        "objection_handling": 70,
        "negotiation": 70,
        "closing": 70,
        "communication": 75,
    },
}

SKILL_LABELS: dict[str, str] = {
    "sql": "SQL & Querying",
    "python": "Python for Data",
    "analytics": "Data Analytics",
    "data_viz": "Data Visualization",
    "statistics": "Statistical Analysis",
    "communication": "Communication",
    "data_cleaning": "Data Cleaning",
    "customer_analysis": "Customer Analysis",
    "segmentation": "Segmentation",
    "hypothesis_testing": "Hypothesis Testing",
    "data_storytelling": "Data Storytelling",
    "html_css": "HTML & CSS",
    "accessibility": "Accessibility",
    "javascript": "JavaScript",
    "async_data": "Async Data Fetching",
    "react": "React",
    "component_design": "Component Design",
    "state_management": "State Management",
    "sales_research": "Sales Research",
    "email_writing": "Email Writing",
    "discovery": "Discovery & Qualification",
    "crm_accuracy": "CRM Accuracy",
    "objection_handling": "Objection Handling",
    "negotiation": "Negotiation",
    "closing": "Closing",
}

# Career-track metadata for the Skill GPS.
#
# TARGET_ROLE_REQUIREMENTS above says what a role DEMANDS; this says what a role
# IS — its display name, which ladder it sits on, and where on that ladder. The
# Skill GPS UI is driven entirely from here (GET /api/skill-gps/roles), because
# the previous hardcoded frontend list had drifted: it offered four Data Analyst
# tiers, two of which had no backend definition at all, and offered nothing for
# the Engineering or Sales simulations this platform actually ships.
#
# `level` orders the ladder inside a track. `domains` maps a Simulation.domain
# string (free text — see app/models/cms.py) onto a track, so a student's
# recommended role follows the simulation they enrolled in.
CAREER_TRACKS: list[dict] = [
    {
        "key": "data",
        "label": "Data Analytics",
        "domains": ["Data Analytics"],
        "roles": [
            {"key": "junior_da", "label": "Junior Data Analyst", "level": 1},
            {"key": "senior_da", "label": "Senior Data Analyst", "level": 2},
        ],
    },
    {
        "key": "frontend",
        "label": "Frontend Engineering",
        "domains": ["Engineering", "IT & Engineering"],
        "roles": [
            {"key": "junior_frontend_dev", "label": "Junior Frontend Developer", "level": 1},
            {"key": "senior_frontend_dev", "label": "Senior Frontend Developer", "level": 2},
        ],
    },
    {
        "key": "sales",
        "label": "Sales",
        "domains": ["Sales"],
        "roles": [
            {"key": "junior_sales_rep", "label": "Junior Sales Rep", "level": 1},
            {"key": "senior_sales_rep", "label": "Senior Sales Rep", "level": 2},
        ],
    },
]

# Flat key -> {label, track, track_label, level} view of CAREER_TRACKS.
ROLE_META: dict[str, dict] = {
    role["key"]: {
        "key": role["key"],
        "label": role["label"],
        "level": role["level"],
        "track": track["key"],
        "track_label": track["label"],
    }
    for track in CAREER_TRACKS
    for role in track["roles"]
}

# Simulation.domain -> track key, derived from CAREER_TRACKS so the two can
# never disagree.
DOMAIN_TO_TRACK: dict[str, str] = {
    domain: track["key"] for track in CAREER_TRACKS for domain in track["domains"]
}

DEFAULT_TARGET_ROLE = "junior_da"

# One category vocabulary for the whole product. The Portfolio page and the
# Skill GPS each used to carry their own partial copy of this, both covering
# only the Data Analytics skills, so every Engineering and Sales skill fell
# through to a default bucket.
SKILL_CATEGORIES: dict[str, str] = {
    # Technical — you build or query the thing itself
    "sql": "Technical",
    "python": "Technical",
    "data_cleaning": "Technical",
    "data_viz": "Technical",
    "html_css": "Technical",
    "javascript": "Technical",
    "react": "Technical",
    "async_data": "Technical",
    "crm_accuracy": "Technical",
    # Domain — knowledge and standards particular to the field
    "analytics": "Domain",
    "customer_analysis": "Domain",
    "segmentation": "Domain",
    "sales_research": "Domain",
    "accessibility": "Domain",
    # Cognitive — judgement calls, architecture, reasoning under uncertainty
    "statistics": "Cognitive",
    "hypothesis_testing": "Cognitive",
    "component_design": "Cognitive",
    "state_management": "Cognitive",
    "discovery": "Cognitive",
    "objection_handling": "Cognitive",
    "negotiation": "Cognitive",
    # Leadership — getting the work across to other people
    "communication": "Leadership",
    "data_storytelling": "Leadership",
    "email_writing": "Leadership",
    "closing": "Leadership",
}

CATEGORY_ORDER: list[str] = ["Technical", "Domain", "Cognitive", "Leadership"]

QUIZ_BONUS_THRESHOLD = 80
QUIZ_BONUS_XP = 20
INACTIVITY_DAYS = 3
